platform: linux
image_resource:
  type: docker-image
  source:
    repository: stephenreed/jenkins-java8-maven-git
    tag: latest

inputs:
  - name: pcf-ers-demo
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-integration

run:
  path: ./pcf-ers-demo/concourse/tasks/prepare-integration.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-integration,
    --version-file, version/number,
    --manifest, pcf-ers-demo/manifest.yml,
    --artifactId, pcf-ers-demo,
    --packaging, jar
  ]
