platform: linux
image_resource:
  type: docker-image
  source:
    repository: stephenreed/jenkins-java8-maven-git
    tag: latest

inputs:
- name: pcf-ers-demo

run:
  path: ./pcf-ers-demo/ci/tasks/unit-test.sh
